### ISSUE TITLE
Address bar does not hide in Safari on iOS

### ISSUE THREAD

**Issue by bkeepers** [chordbook/chordbook#1351]
Address bar should collapse when scrolling down the page in Safari on iOS. This is a known issue with Ionic: https://github.com/ionic-team/ionic-framework/issues/19081

I've tried several of the workarounds touted on the web, and couldn't get any of them to work.

```css
html {
  position: relative;
  height: calc(100vh + 1px); /*I also tried: 101vh and 200vh; */
  overflow: hidden;
}
```

```js
window.requestAnimationFrame(() => { window.scrollTo(0, 1) })
```
